//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aero.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Aero.Model;
    
    public partial class AeroContainer : DbContext
    {
        public AeroContainer()
            : base("name=AeroContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Vendor> Vendors { get; set; }
        public DbSet<Contact> Contacts { get; set; }
        public DbSet<Part> Parts { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<RFQ> RFQs { get; set; }
        public DbSet<PO> POes { get; set; }
        public DbSet<Priority> Priorities { get; set; }
        public DbSet<RFQState> RFQStates { get; set; }
    }
}
