//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aero.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Part
    {
        public Part()
        {
            this.Qty = 0;
            this.RFQs = new HashSet<RFQ>();
            this.POes = new HashSet<PO>();
        }
    
        public int Id { get; set; }
        public string PartNumber { get; set; }
        public string Description { get; set; }
        public short Qty { get; set; }
        public Condition Condition { get; set; }
        public decimal Price { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string Source { get; set; }
        public string NSN { get; set; }
        public string Model { get; set; }
        public int VendorId { get; set; }
    
        public virtual Vendor Vendor { get; set; }
        public virtual ICollection<RFQ> RFQs { get; set; }
        public virtual ICollection<PO> POes { get; set; }
    }
}
