//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aero.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PO
    {
        public int Id { get; set; }
        public string Number { get; set; }
        public decimal UnitPrice { get; set; }
        public short Qty { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public string Comment { get; set; }
        public int Customer_Id { get; set; }
    
        public virtual Part Part { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
