//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aero.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        public Vendor()
        {
            this.Parts = new HashSet<Part>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int ContactId { get; set; }
    
        public virtual ICollection<Part> Parts { get; set; }
        public virtual Contact Contact { get; set; }
    }
}
